
[FILE_INFO]
FILE_VER = 1
FILE_USE = 1
COUNTRY_NAME = UN

KEY_COUNT = 1
KEY_LIST = PLU_STRUCTURE,
MODEL_COUNT = 1
MODEL_LIST = 5000,

[SUBSTRUCTURE_INFO]
SUBSTRUCTURE_USE = 0
SUBSTRUCTURE_COUNT = 0
SUBSTRUCTURE_ITEM1_MODEL = 
SUBSTRUCTURE_ITEM1_FILE =

[PLU_STRUCTURE_5000]
PLU_STRUCTURE_VER = 1
PLU_STRUCTURE_USE =2
PLU_STRUCTURE_CODE = 1100
PLU_STRUCTURE_ITEM_COUNT = 51

;CODE - Identify number
;Name - Name char string
;Size - Variable size
;Leng - Char length
;Min  - Minimize of value
;Max  - Maximize of value
;Dec  - Decimal point count
;Level - Important level, 0: Don't Use, 1:Essential, 2:Necessity, 3:maybe it can't use
;Default - Default value
;Datatype- DEC:10, HEX:16, OCT:8, BIN:2, CHR:1 (String)
;Dataclas- STRING:1, NUMERIC:2, WEIGHT:3, PRICE:4, PERCENT:5, DATE:6, TIME:7

PLU_FIELD1_CODE =1
PLU_FIELD1_NAME = Department No
PLU_FIELD1_SIZE = 2
PLU_FIELD1_LENG = 2
PLU_FIELD1_MIN  = 1
PLU_FIELD1_MAX  = 99
PLU_FIELD1_DEC  = 0
PLU_FIELD1_LEVEL=1
PLU_FIELD1_DEFAULT = 1
PLU_FIELD1_DATATYPE = 10
PLU_FIELD1_DATACLAS = 2

PLU_FIELD2_CODE =2
PLU_FIELD2_NAME = PLU No
PLU_FIELD2_SIZE = 4
PLU_FIELD2_LENG = 5
PLU_FIELD2_MIN  = 0
PLU_FIELD2_MAX  = 99999
PLU_FIELD2_DEC  = 0
PLU_FIELD2_LEVEL=1
PLU_FIELD2_DEFAULT = 1
PLU_FIELD2_DATATYPE = 10
PLU_FIELD2_DATACLAS = 2

PLU_FIELD3_CODE =3
PLU_FIELD3_NAME = Prefix
PLU_FIELD3_SIZE = 10
PLU_FIELD3_LENG = 2
PLU_FIELD3_MIN  = 0
PLU_FIELD3_MAX  = 0
PLU_FIELD3_DEC  = 0
PLU_FIELD3_LEVEL=2
PLU_FIELD3_DEFAULT = 
PLU_FIELD3_DATATYPE = 1
PLU_FIELD3_DATACLAS = 1

PLU_FIELD4_CODE =4
PLU_FIELD4_NAME = PLU Type
PLU_FIELD4_SIZE = 1
PLU_FIELD4_LENG = 1
PLU_FIELD4_MIN  = 1
PLU_FIELD4_MAX  = 4
PLU_FIELD4_DEC  = 0
PLU_FIELD4_LEVEL=1
PLU_FIELD4_DEFAULT = 1
PLU_FIELD4_DATATYPE = 10
PLU_FIELD4_DATACLAS = 2

PLU_FIELD5_CODE =5
PLU_FIELD5_NAME = Unit weight
PLU_FIELD5_SIZE = 1
PLU_FIELD5_LENG = 1
PLU_FIELD5_MIN  = 1
PLU_FIELD5_MAX  = 3
PLU_FIELD5_DEC  = 0
PLU_FIELD5_LEVEL=1
PLU_FIELD5_DEFAULT = 1
PLU_FIELD5_DATATYPE = 10
PLU_FIELD5_DATACLAS = 2

PLU_FIELD6_CODE =6
PLU_FIELD6_NAME = price
PLU_FIELD6_SIZE = 4
PLU_FIELD6_LENG = 6
PLU_FIELD6_MIN  = 0
PLU_FIELD6_MAX  = 999999
PLU_FIELD6_DEC  = 0
PLU_FIELD6_LEVEL=1
PLU_FIELD6_DEFAULT = 0
PLU_FIELD6_DATATYPE = 10
PLU_FIELD6_DATACLAS = 4

PLU_FIELD7_CODE =8
PLU_FIELD7_NAME = Tax no
PLU_FIELD7_SIZE = 2
PLU_FIELD7_LENG = 1
PLU_FIELD7_MIN  = 1
PLU_FIELD7_MAX  = 9
PLU_FIELD7_DEC  = 0
PLU_FIELD7_LEVEL=2
PLU_FIELD7_DEFAULT = 0
PLU_FIELD7_DATATYPE = 10
PLU_FIELD7_DATACLAS = 2

PLU_FIELD8_CODE =9
PLU_FIELD8_NAME = Group no
PLU_FIELD8_SIZE = 2
PLU_FIELD8_LENG = 2
PLU_FIELD8_MIN  = 0
PLU_FIELD8_MAX  = 99
PLU_FIELD8_DEC  = 0
PLU_FIELD8_LEVEL=1
PLU_FIELD8_DEFAULT = 0
PLU_FIELD8_DATATYPE = 10
PLU_FIELD8_DATACLAS = 2

PLU_FIELD9_CODE =10
PLU_FIELD9_NAME = Name
PLU_FIELD9_SIZE = 100
PLU_FIELD9_LENG = 40
PLU_FIELD9_MIN  = 0
PLU_FIELD9_MAX  = 0
PLU_FIELD9_DEC  = 0
PLU_FIELD9_LEVEL=1
PLU_FIELD9_DEFAULT = 
PLU_FIELD9_DATATYPE = 1
PLU_FIELD9_DATACLAS = 1

PLU_FIELD10_CODE =11
PLU_FIELD10_NAME = Itemcode
PLU_FIELD10_SIZE = 4
PLU_FIELD10_LENG = 6
PLU_FIELD10_MIN  = 0
PLU_FIELD10_MAX  = 999999
PLU_FIELD10_DEC  = 0
PLU_FIELD10_LEVEL=1
PLU_FIELD10_DEFAULT = 0
PLU_FIELD10_DATATYPE = 10
PLU_FIELD10_DATACLAS = 2

PLU_FIELD11_CODE =12
PLU_FIELD11_NAME = Tare no
PLU_FIELD11_SIZE = 2
PLU_FIELD11_LENG = 2
PLU_FIELD11_MIN  = 0
PLU_FIELD11_MAX  = 99
PLU_FIELD11_DEC  = 0
PLU_FIELD11_LEVEL=2
PLU_FIELD11_DEFAULT = 0
PLU_FIELD11_DATATYPE = 10
PLU_FIELD11_DATACLAS = 2

PLU_FIELD12_CODE =13
PLU_FIELD12_NAME = Tare
PLU_FIELD12_SIZE = 4
PLU_FIELD12_LENG = 6
PLU_FIELD12_MIN  = 0
PLU_FIELD12_MAX  = 999999
PLU_FIELD12_DEC  = 0
PLU_FIELD12_LEVEL=1
PLU_FIELD12_DEFAULT = 0
PLU_FIELD12_DATATYPE = 10
PLU_FIELD12_DATACLAS = 3

PLU_FIELD13_CODE =14
PLU_FIELD13_NAME = Pieces
PLU_FIELD13_SIZE = 2
PLU_FIELD13_LENG = 3
PLU_FIELD13_MIN  = 0
PLU_FIELD13_MAX  = 999
PLU_FIELD13_DEC  = 0
PLU_FIELD13_LEVEL=1
PLU_FIELD13_DEFAULT = 0
PLU_FIELD13_DATATYPE = 10
PLU_FIELD13_DATACLAS = 2

PLU_FIELD14_CODE =15
PLU_FIELD14_NAME = Qty unit no
PLU_FIELD14_SIZE = 1
PLU_FIELD14_LENG = 1
PLU_FIELD14_MIN  = 0
PLU_FIELD14_MAX  = 8
PLU_FIELD14_DEC  = 0
PLU_FIELD14_LEVEL=1
PLU_FIELD14_DEFAULT = 0
PLU_FIELD14_DATATYPE = 10
PLU_FIELD14_DATACLAS = 2

PLU_FIELD15_CODE =16
PLU_FIELD15_NAME = Sell by date
PLU_FIELD15_SIZE = 2
PLU_FIELD15_LENG = 4
PLU_FIELD15_MIN  = 0
PLU_FIELD15_MAX  = 9999
PLU_FIELD15_DEC  = 0
PLU_FIELD15_LEVEL=1
PLU_FIELD15_DEFAULT = 0
PLU_FIELD15_DATATYPE = 10
PLU_FIELD15_DATACLAS = 2

PLU_FIELD16_CODE =17
PLU_FIELD16_NAME = Sell by time
PLU_FIELD16_SIZE = 2
PLU_FIELD16_LENG = 2
PLU_FIELD16_MIN  = 0
PLU_FIELD16_MAX  = 99
PLU_FIELD16_DEC  = 0
PLU_FIELD16_LEVEL=1
PLU_FIELD16_DEFAULT = 0
PLU_FIELD16_DATATYPE = 10
PLU_FIELD16_DATACLAS = 2

PLU_FIELD17_CODE =18
PLU_FIELD17_NAME = Packed Date
PLU_FIELD17_SIZE = 2
PLU_FIELD17_LENG = 3
PLU_FIELD17_MIN  = 0
PLU_FIELD17_MAX  = 999
PLU_FIELD17_DEC  = 0
PLU_FIELD17_LEVEL=1
PLU_FIELD17_DEFAULT = 0
PLU_FIELD17_DATATYPE = 10
PLU_FIELD17_DATACLAS = 2

PLU_FIELD18_CODE =19
PLU_FIELD18_NAME = Packed Time
PLU_FIELD18_SIZE = 2
PLU_FIELD18_LENG = 2
PLU_FIELD18_MIN  = 0
PLU_FIELD18_MAX  = 99
PLU_FIELD18_DEC  = 0
PLU_FIELD18_LEVEL=2
PLU_FIELD18_DEFAULT = 0
PLU_FIELD18_DATATYPE = 10
PLU_FIELD18_DATACLAS = 2

PLU_FIELD19_CODE =20
PLU_FIELD19_NAME = Produce date
PLU_FIELD19_SIZE = 2
PLU_FIELD19_LENG = 3
PLU_FIELD19_MIN  = 0
PLU_FIELD19_MAX  = 999
PLU_FIELD19_DEC  = 0
PLU_FIELD19_LEVEL=2
PLU_FIELD19_DEFAULT = 0
PLU_FIELD19_DATATYPE = 10
PLU_FIELD19_DATACLAS = 2

PLU_FIELD20_CODE =22
PLU_FIELD20_NAME = Cook by date
PLU_FIELD20_SIZE = 2
PLU_FIELD20_LENG = 4
PLU_FIELD20_MIN  = 0
PLU_FIELD20_MAX  = 9999
PLU_FIELD20_DEC  = 0
PLU_FIELD20_LEVEL=2
PLU_FIELD20_DEFAULT = 0
PLU_FIELD20_DATATYPE = 10
PLU_FIELD20_DATACLAS = 2

PLU_FIELD21_CODE =23
PLU_FIELD21_NAME = Tare % limit
PLU_FIELD21_SIZE = 4
PLU_FIELD21_LENG = 5
PLU_FIELD21_MIN  = 0
PLU_FIELD21_MAX  = 99999
PLU_FIELD21_DEC  = 2
PLU_FIELD21_LEVEL=2
PLU_FIELD21_DEFAULT = 0
PLU_FIELD21_DATATYPE =10
PLU_FIELD21_DATACLAS = 5

PLU_FIELD22_CODE =24
PLU_FIELD22_NAME = % Tare
PLU_FIELD22_SIZE = 4
PLU_FIELD22_LENG = 5
PLU_FIELD22_MIN  = 0
PLU_FIELD22_MAX  = 99999
PLU_FIELD22_DEC  = 2
PLU_FIELD22_LEVEL=2
PLU_FIELD22_DEFAULT = 0
PLU_FIELD22_DATATYPE = 10
PLU_FIELD22_DATACLAS = 5

PLU_FIELD23_CODE =25
PLU_FIELD23_NAME = Ingredient no
PLU_FIELD23_SIZE = 2
PLU_FIELD23_LENG = 3
PLU_FIELD23_MIN  = 0
PLU_FIELD23_MAX  = 999
PLU_FIELD23_DEC  = 0
PLU_FIELD23_LEVEL=1
PLU_FIELD23_DEFAULT = 0
PLU_FIELD23_DATATYPE = 10
PLU_FIELD23_DATACLAS = 2

PLU_FIELD24_CODE =26
PLU_FIELD24_NAME = Use fixed price type
PLU_FIELD24_SIZE = 1
PLU_FIELD24_LENG = 1
PLU_FIELD24_MIN  = 0
PLU_FIELD24_MAX  = 1
PLU_FIELD24_DEC  = 0
PLU_FIELD24_LEVEL=1
PLU_FIELD24_DEFAULT = 0
PLU_FIELD24_DATATYPE = 10
PLU_FIELD24_DATACLAS = 2

PLU_FIELD25_CODE =30
PLU_FIELD25_NAME = Name2
PLU_FIELD25_SIZE = 100
PLU_FIELD25_LENG = 40
PLU_FIELD25_MIN  = 0
PLU_FIELD25_MAX  = 0
PLU_FIELD25_DEC  = 0
PLU_FIELD25_LEVEL=1
PLU_FIELD25_DEFAULT = 
PLU_FIELD25_DATATYPE = 1
PLU_FIELD25_DATACLAS = 1

PLU_FIELD26_CODE =31
PLU_FIELD26_NAME = Name3
PLU_FIELD26_SIZE = 100
PLU_FIELD26_LENG = 40
PLU_FIELD26_MIN  = 0
PLU_FIELD26_MAX  = 0
PLU_FIELD26_DEC  = 0
PLU_FIELD26_LEVEL=1
PLU_FIELD26_DEFAULT = 
PLU_FIELD26_DATATYPE = 1
PLU_FIELD26_DATACLAS = 1

PLU_FIELD27_CODE =35
PLU_FIELD27_NAME = Traceability no
PLU_FIELD27_SIZE = 2
PLU_FIELD27_LENG = 999
PLU_FIELD27_MIN  = 0
PLU_FIELD27_MAX  = 999
PLU_FIELD27_DEC  = 0
PLU_FIELD27_LEVEL=2
PLU_FIELD27_DEFAULT = 0
PLU_FIELD27_DATATYPE = 10
PLU_FIELD27_DATACLAS = 2

PLU_FIELD28_CODE =36
PLU_FIELD28_NAME = Picture no
PLU_FIELD28_SIZE = 2
PLU_FIELD28_LENG = 2
PLU_FIELD28_MIN  = 0
PLU_FIELD28_MAX  = 99
PLU_FIELD28_DEC  = 0
PLU_FIELD28_LEVEL=0
PLU_FIELD28_DEFAULT = 1
PLU_FIELD28_DATATYPE = 10
PLU_FIELD28_DATACLAS = 2

PLU_FIELD29_CODE =49
PLU_FIELD29_NAME = Ext. Barcode
PLU_FIELD29_SIZE = 50
PLU_FIELD29_LENG = 20
PLU_FIELD29_MIN  = 0
PLU_FIELD29_MAX  = 0
PLU_FIELD29_DEC  = 0
PLU_FIELD29_LEVEL=2
PLU_FIELD29_DEFAULT = 
PLU_FIELD29_DATATYPE = 1
PLU_FIELD29_DATACLAS = 1

PLU_FIELD30_CODE =50
PLU_FIELD30_NAME = Bonus
PLU_FIELD30_SIZE = 2
PLU_FIELD30_LENG = 3
PLU_FIELD30_MIN  = 0
PLU_FIELD30_MAX  = 999
PLU_FIELD30_DEC  = 0
PLU_FIELD30_LEVEL=2
PLU_FIELD30_DEFAULT = 0
PLU_FIELD30_DATATYPE = 10
PLU_FIELD30_DATACLAS = 2

PLU_FIELD31_CODE =55
PLU_FIELD31_NAME = Origin No
PLU_FIELD31_SIZE = 2
PLU_FIELD31_LENG = 3
PLU_FIELD31_MIN  = 0
PLU_FIELD31_MAX  = 500
PLU_FIELD31_DEC  = 0
PLU_FIELD31_LEVEL=1
PLU_FIELD31_DEFAULT = 0
PLU_FIELD31_DATATYPE = 10
PLU_FIELD31_DATACLAS = 2

PLU_FIELD32_CODE =60
PLU_FIELD32_NAME = # of LinkPLU
PLU_FIELD32_SIZE = 2
PLU_FIELD32_LENG = 1
PLU_FIELD32_MIN  = 0
PLU_FIELD32_MAX  = 2
PLU_FIELD32_DEC  = 0
PLU_FIELD32_LEVEL=2
PLU_FIELD32_DEFAULT = 0
PLU_FIELD32_DATATYPE = 10
PLU_FIELD32_DATACLAS = 2

PLU_FIELD33_CODE =61
PLU_FIELD33_NAME = Link PLU1 Dept
PLU_FIELD33_SIZE = 2
PLU_FIELD33_LENG = 2
PLU_FIELD33_MIN  = 0
PLU_FIELD33_MAX  = 99
PLU_FIELD33_DEC  = 0
PLU_FIELD33_LEVEL=2
PLU_FIELD33_DEFAULT = 0
PLU_FIELD33_DATATYPE = 10
PLU_FIELD33_DATACLAS = 2

PLU_FIELD34_CODE =62
PLU_FIELD34_NAME = Link PLU2 Dept
PLU_FIELD34_SIZE = 2
PLU_FIELD34_LENG = 2
PLU_FIELD34_MIN  = 0
PLU_FIELD34_MAX  = 99
PLU_FIELD34_DEC  = 0
PLU_FIELD34_LEVEL=2
PLU_FIELD34_DEFAULT = 0
PLU_FIELD34_DATATYPE = 10
PLU_FIELD34_DATACLAS = 2

PLU_FIELD35_CODE =64
PLU_FIELD35_NAME = Coupled PLU Dept
PLU_FIELD35_SIZE = 2
PLU_FIELD35_LENG = 2
PLU_FIELD35_MIN  = 0
PLU_FIELD35_MAX  = 99
PLU_FIELD35_DEC  = 0
PLU_FIELD35_LEVEL=2
PLU_FIELD35_DEFAULT = 0
PLU_FIELD35_DATATYPE = 10
PLU_FIELD35_DATACLAS = 2

PLU_FIELD36_CODE =65
PLU_FIELD36_NAME = Link PLU1 No
PLU_FIELD36_SIZE = 4
PLU_FIELD36_LENG = 6
PLU_FIELD36_MIN  = 0
PLU_FIELD36_MAX  = 999999
PLU_FIELD36_DEC  = 0
PLU_FIELD36_LEVEL=2
PLU_FIELD36_DEFAULT = 0
PLU_FIELD36_DATATYPE = 10
PLU_FIELD36_DATACLAS = 2

PLU_FIELD37_CODE =66
PLU_FIELD37_NAME = Link PLU2 No
PLU_FIELD37_SIZE = 4
PLU_FIELD37_LENG = 6
PLU_FIELD37_MIN  = 1
PLU_FIELD37_MAX  = 999999
PLU_FIELD37_DEC  = 0
PLU_FIELD37_LEVEL=2
PLU_FIELD37_DEFAULT = 0
PLU_FIELD37_DATATYPE = 10
PLU_FIELD37_DATACLAS = 2

PLU_FIELD38_CODE =68
PLU_FIELD38_NAME = Coupled PLU No
PLU_FIELD38_SIZE = 4
PLU_FIELD38_LENG = 6
PLU_FIELD38_MIN  = 0
PLU_FIELD38_MAX  = 999999
PLU_FIELD38_DEC  = 0
PLU_FIELD38_LEVEL=2
PLU_FIELD38_DEFAULT = 0
PLU_FIELD38_DATATYPE = 10
PLU_FIELD38_DATACLAS = 2

PLU_FIELD39_CODE =69
PLU_FIELD39_NAME = Reference PLU No
PLU_FIELD39_SIZE = 4
PLU_FIELD39_LENG = 6
PLU_FIELD39_MIN  = 0
PLU_FIELD39_MAX  = 999999
PLU_FIELD39_DEC  = 0
PLU_FIELD39_LEVEL=2
PLU_FIELD39_DEFAULT = 0
PLU_FIELD39_DATATYPE = 10
PLU_FIELD39_DATACLAS = 2

PLU_FIELD40_CODE =70
PLU_FIELD40_NAME = Nutrifact no
PLU_FIELD40_SIZE = 2
PLU_FIELD40_LENG = 3
PLU_FIELD40_MIN  = 0
PLU_FIELD40_MAX  = 500
PLU_FIELD40_DEC  = 0
PLU_FIELD40_LEVEL=2
PLU_FIELD40_DEFAULT = 0
PLU_FIELD40_DATATYPE = 10
PLU_FIELD40_DATACLAS = 2

PLU_FIELD41_CODE =71
PLU_FIELD41_NAME = Reference PLU Dept
PLU_FIELD41_SIZE = 2
PLU_FIELD41_LENG = 2
PLU_FIELD41_MIN  = 0
PLU_FIELD41_MAX  = 99
PLU_FIELD41_DEC  = 0
PLU_FIELD41_LEVEL=2
PLU_FIELD41_DEFAULT = 0
PLU_FIELD41_DATATYPE = 10
PLU_FIELD41_DATACLAS = 2

PLU_FIELD42_CODE =80
PLU_FIELD42_NAME = Label No
PLU_FIELD42_SIZE = 2
PLU_FIELD42_LENG = 2
PLU_FIELD42_MIN  = 0
PLU_FIELD42_MAX  = 99
PLU_FIELD42_DEC  = 0
PLU_FIELD42_LEVEL=1
PLU_FIELD42_DEFAULT = 0
PLU_FIELD42_DATATYPE = 10
PLU_FIELD42_DATACLAS = 2

PLU_FIELD43_CODE =81
PLU_FIELD43_NAME = Aux Label No
PLU_FIELD43_SIZE = 2
PLU_FIELD43_LENG = 2
PLU_FIELD43_MIN  = 0
PLU_FIELD43_MAX  = 99
PLU_FIELD43_DEC  = 0
PLU_FIELD43_LEVEL=1
PLU_FIELD43_DEFAULT = 0
PLU_FIELD43_DATATYPE = 10
PLU_FIELD43_DATACLAS = 2

PLU_FIELD44_CODE =85
PLU_FIELD44_NAME = Barcode No
PLU_FIELD44_SIZE = 2
PLU_FIELD44_LENG = 2
PLU_FIELD44_MIN  = 0
PLU_FIELD44_MAX  = 99
PLU_FIELD44_DEC  = 0
PLU_FIELD44_LEVEL=1
PLU_FIELD44_DEFAULT = 0
PLU_FIELD44_DATATYPE = 10
PLU_FIELD44_DATACLAS = 2

PLU_FIELD45_CODE =86
PLU_FIELD45_NAME = Barcode2 No
PLU_FIELD45_SIZE = 2
PLU_FIELD45_LENG = 6
PLU_FIELD45_MIN  = 0
PLU_FIELD45_MAX  = 999999
PLU_FIELD45_DEC  = 0
PLU_FIELD45_LEVEL=2
PLU_FIELD45_DEFAULT = 0
PLU_FIELD45_DATATYPE = 10
PLU_FIELD45_DATACLAS = 2

PLU_FIELD46_CODE =90
PLU_FIELD46_NAME = Sales Msg No
PLU_FIELD46_SIZE = 2
PLU_FIELD46_LENG = 2
PLU_FIELD46_MIN  = 0
PLU_FIELD46_MAX  = 99
PLU_FIELD46_DEC  = 0
PLU_FIELD46_LEVEL=2
PLU_FIELD46_DEFAULT = 0
PLU_FIELD46_DATATYPE = 10
PLU_FIELD46_DATACLAS = 2

PLU_FIELD47_CODE =91
PLU_FIELD47_NAME = SpecialPrice
PLU_FIELD47_SIZE = 4
PLU_FIELD47_LENG = 6
PLU_FIELD47_MIN  = 0
PLU_FIELD47_MAX  = 999999
PLU_FIELD47_DEC  = 0
PLU_FIELD47_LEVEL=1
PLU_FIELD47_DEFAULT = 0
PLU_FIELD47_DATATYPE = 10
PLU_FIELD47_DATACLAS = 4

PLU_FIELD48_CODE = 99
PLU_FIELD48_NAME = Direct Ingredient
PLU_FIELD48_SIZE = 1024
PLU_FIELD48_LENG = 300
PLU_FIELD48_MIN  = 0
PLU_FIELD48_MAX  = 0
PLU_FIELD48_DEC  = 0
PLU_FIELD48_LEVEL = 2
PLU_FIELD48_DEFAULT = 0
PLU_FIELD48_DATATYPE = 1
PLU_FIELD48_DATACLAS = 1

PLU_FIELD49_CODE = 100
PLU_FIELD49_NAME = FixedWeight
PLU_FIELD49_SIZE = 4
PLU_FIELD49_LENG = 5
PLU_FIELD49_MIN  = 0
PLU_FIELD49_MAX  = 99999
PLU_FIELD49_DEC  = 0
PLU_FIELD49_LEVEL=1
PLU_FIELD49_DEFAULT = 0
PLU_FIELD49_DATATYPE = 10
PLU_FIELD49_DATACLAS = 3

PLU_FIELD50_CODE =101
PLU_FIELD50_NAME = PLU Picture
PLU_FIELD50_SIZE = 50
PLU_FIELD50_LENG = 50
PLU_FIELD50_MIN  = 0
PLU_FIELD50_MAX  = 0
PLU_FIELD50_DEC  = 0
PLU_FIELD50_LEVEL=1
PLU_FIELD50_DEFAULT = 0
PLU_FIELD50_DATATYPE = 1
PLU_FIELD50_DATACLAS = 1

PLU_FIELD51_CODE =102
PLU_FIELD51_NAME = SafetyCode
PLU_FIELD51_LEVEL=0

